name: pokemon_application
description: Simple pokemon list app from API

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  dio: ^4.0.6
  get_it: ^7.6.0
  http: ^0.13.5  
  flutter_bloc: ^8.1.3
  
dev_dependencies: 
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true  # Add flutter_bloc package as a dependency
  assets:
    - assets/svg/
# Other configurations...
